package vimalesh.fire;

import android.graphics.Bitmap;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

public class GeneratorActivity extends AppCompatActivity {
    EditText text;
    Button gen_btn;
    ImageView image;
    String text2Qr;
    String h;
    private Button scan_btn, confirmm;
    FirebaseAuth mauth;
    FirebaseDatabase database = FirebaseDatabase.getInstance();
    UserInformation uInfo = new UserInformation();

    //private static final String TAG = "displayActivty";
    //    private FirebaseDatabase mref;
    //private ArrayList<String> mmlistview = new ArrayList<>();
    //private ListView mlistview;
    String user_id;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_generator);
        text = (EditText) findViewById(R.id.text);
        confirmm = (Button) findViewById(R.id.button3);
        gen_btn = (Button) findViewById(R.id.gen_btn);
        image = (ImageView) findViewById(R.id.image);
        gen_btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                text2Qr = text.getText().toString().trim();

                MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
                try {
                    BitMatrix bitMatrix = multiFormatWriter.encode(text2Qr, BarcodeFormat.QR_CODE, 200, 200);
                    BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
                    Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);
                    image.setImageBitmap(bitmap);
                } catch (WriterException e) {
                    e.printStackTrace();
                }


            }
        });
        confirmm.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                FirebaseUser currentFirebaseUser = FirebaseAuth.getInstance().getCurrentUser();

                user_id = currentFirebaseUser.getUid();

                //FirebaseUser currentFirebaseUser = FirebaseAuth.getInstance().getCurrentUser();
                //user_id = currentFirebaseUser.getUid();
                //  Toast.makeText(GeneratorActivity.this, user_id, Toast.LENGTH_LONG).show();
                //String y = Integer.toString(text2Qr);
                //Toast.makeText(getApplicationContext(), text2Qr, Toast.LENGTH_LONG).show();
                DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
//DatabaseReference reft=ref.child("user");
                ref.addValueEventListener(new ValueEventListener() {
                    int i = 1;

                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {
                        if (i > 0) {
                                showData(dataSnapshot);
//String er="text";
                            //for (DataSnapshot ds : dataSnapshot.getChildren()) {
                              //  er = (String) ds.child("balance").getValue();
    //                            Toast.makeText(getApplicationContext(), er, Toast.LENGTH_LONG).show();

//                                uInfo.setbalance(ds.child(user_id).getValue(UserInformation.class).getbalance());

                            }


                            i--;

                    }

                    @Override
                    public void onCancelled(DatabaseError databaseError) {

                    }
                });
            }
        });
    }



    //Toast.makeText(this,user_id,Toast.LENGTH_LONG).show();
    //String barcode = result.getBarcodeImagePath();
    //Toast.makeText(this, user_id, Toast.LENGTH_LONG).show();

    //DatabaseReference myRef1 = database.getReference().child("user").child(user_id); //Getting root reference
    //Toast.makeText(this, (CharSequence) my, Toast.LENGTH_LONG).show();
    //String key = myRef1.push().getKey();           //this returns the unique key generated by firebase
    // myRef1.child("barcode").setValue(hai);
    //myRef1.child(key).child("barcode number").setValue(barcode);
/*    DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
    // = FirebaseDatabase.getInstance();
    mlistview = (ListView) findViewById(hai);
    //currentFirebaseUser = FirebaseAuth.getInstance().getCurrentUser();
    //userid = currentFirebaseUser.getUid();

}
*/

    private void showData(DataSnapshot dataSnapshot) {

        for (DataSnapshot ds : dataSnapshot.getChildren()) {

            //          uInfo.setemail(ds.getValue(UserInformation.class).getemail()); //set the email
            //uInfo.setbarcode(ds.child(user_id).getValue(UserInformation.class).getbarcode()); //set the name
            uInfo.setbalance(ds.child(user_id).getValue(UserInformation.class).getbalance()); //set the phone_num
            //
            break;
        }
        String er = uInfo.getbalance();
        int j = Integer.parseInt(er);
        //String t = uInfo.getbarcode();
        int y = Integer.parseInt(text2Qr);
        j = j + y;
        //int ya=
        String h = Integer.toString(j);


    DatabaseReference myRef1 = database.getReference().child("user").child(user_id); //Getting root reference
        String key = myRef1.push().getKey();           //this returns the unique key generated by firebase
        myRef1.child("balance").setValue(h);


     Toast.makeText(getApplicationContext(), h, Toast.LENGTH_LONG).show();
        //display all the information
        //Log.d(TAG, "showData: name: " + uInfo.getname());
        //Log.d(TAG, "showData: email: " + uInfo.getemail());
        //Log.d(TAG, "showData: phone_num: " + uInfo.getPhone_num());

        //ArrayList<String> array = new ArrayList<>();
    }
}






